### ISSUE TITLE
llvm/Value.h: file not found

### ISSUE THREAD

**Issue by akash-vartak** [lsegal/my_toy_compiler#31]
Please tell me which llvm and clang versions to install!!
And my other error
My error:
```
akash007@ubuntu:~/ToyLanguage$ g++ -o parser parser.cpp tokens.cpp main.cpp  
In file included from parser.y:2:0:
node.h:3:27: fatal error: llvm/IR/Value.h: No such file or directory
 #include <llvm/IR/Value.h>
                           ^
compilation terminated.
In file included from tokens.l:3:0:
node.h:3:27: fatal error: llvm/IR/Value.h: No such file or directory
 #include <llvm/IR/Value.h>
                           ^
compilation terminated.
In file included from main.cpp:2:0:
node.h:3:27: fatal error: llvm/IR/Value.h: No such file or directory
 #include <llvm/IR/Value.h>
                           ^
compilation terminated.
```
Help me please!!

**Comment by lsegal** [comment]
The latest pull request added LLVM 3.7 support, though this changes from time to time. That said, `llvm/IR/Value.h` has probably been around for quite a while, so if you're not finding that it seems like your LLVM install may not be correctly setup.

Unfortunately this project assumes that you know how to correctly install and use LLVM/clang, so this is something you will have to debug on your own. Sorry!

**Comment by akash-vartak** [comment]
The problem is I have installed llvm by
```apt-get install llvm``` (Ubuntu 14.04)
and the error still persists.

Could me kindly link me to a good installation reference

**Comment by lsegal** [comment]
As with most Ubuntu packages, headers and static libs are usually found in a separate `-devel` package, but I don't know if this is the case for LLVM. I would recommend Googling for this information specific to your OS, since the OS makes all the difference, and I don't have any info experience doing this on Ubuntu.

**Comment by akash-vartak** [comment]
I checked google for solutions, nothing helpful. Even the llvm documentation is haphazard, disorganized.

**Comment by Higuoxing** [comment]
You should include the Value.h file by
```c++
#include <llvm/IR/Value.h>
```
But I missed some errors after compiled, still trying to fix it

**Comment by Higuoxing** [comment]
Sorry for not noticing this is a closed issue and repo owner has given the correct answer. Nice tutorial!!
